### ISSUE TITLE
Feature Request: CalDAV support for Tasks and Events

### ISSUE THREAD

**Issue by jummo** [AndrewRoe34/quick-sched#81]
CalDAV support for syncing tasks and events would be great.

Maybe with [vdirsyncer](https://github.com/pimutils/vdirsyncer) as backend.

**Comment by AndrewRoe34** [comment]
Interesting! I'll definitely take a look at it.

What Calendar system do you happen to use?

**Comment by jummo** [comment]
> Interesting! I'll definitely take a look at it.
> 
> What Calendar system do you happen to use?

Different clients on different systems.
Their is good CalDAV support for Linux, in Android you have DAVx⁵ and itś native in iOS/macOS.
And with Radicale you can host it yourself.

**Comment by AndrewRoe34** [comment]
After looking into it further, we will not be supporting this.

Thank you for the suggestion regardless!
